#!/usr/bin/env python3.11
"""
Generate README.md from README.template.md + readme.config.toml.

Usage from project root:
    python3 tools/generate_readme.py

Common options:
    python3 tools/generate_readme.py --check
    python3 tools/generate_readme.py --output README.generated.md
    python3 tools/generate_readme.py --root /path/to/project
"""

from __future__ import annotations

import argparse
import difflib
import re
import sys
from pathlib import Path

try:
    import tomllib  # Python 3.11+
except ModuleNotFoundError:  # pragma: no cover
    tomllib = None


START = "<!-- AUTO-GENERATED-REFERENCE-LINKS:START -->"
END = "<!-- AUTO-GENERATED-REFERENCE-LINKS:END -->"


def relpath(path: Path, root: Path) -> str:
    try:
        return path.relative_to(root).as_posix()
    except ValueError:
        return path.as_posix()


def load_toml(path: Path) -> dict:
    if tomllib is None:
        raise RuntimeError("Python 3.11+ is required for tomllib, or install a TOML parser.")
    with path.open("rb") as f:
        return tomllib.load(f)


def render_inline_placeholders(template: str, cfg: dict) -> str:
    project = cfg.get("project", {})
    paths = cfg.get("paths", {})
    docs_root = paths.get("docs_root", "docs").strip("/")
    assets_root = paths.get("assets_root", "assets").strip("/")

    replacements = {
        "project.title": project.get("title", ""),
        "project.name": project.get("name", ""),
        "project.description": project.get("description", ""),
    }

    for key, value in cfg.get("docs", {}).items():
        replacements[f"doc.{key}"] = f"./{docs_root}/{value}".replace("\\", "/")

    for key, value in cfg.get("assets", {}).items():
        replacements[f"asset.{key}"] = f"./{assets_root}/{value}".replace("\\", "/")

    def replace(match: re.Match[str]) -> str:
        token = match.group(1).strip()
        if token not in replacements:
            raise KeyError(f"Unknown template placeholder: {{{{ {token} }}}}")
        return replacements[token]

    return re.sub(r"\{\{\s*([^}]+)\s*\}\}", replace, template)


def build_reference_block(cfg: dict) -> str:
    paths = cfg.get("paths", {})
    docs_root = paths.get("docs_root", "docs").strip("/")
    assets_root = paths.get("assets_root", "assets").strip("/")

    lines = [START, "<!-- Generated by tools/generate_readme.py. Edit readme.config.toml, not this block. -->", ""]

    if cfg.get("docs"):
        lines.append("<!-- Docs -->")
        for key in sorted(cfg["docs"].keys()):
            target = f"./{docs_root}/{cfg['docs'][key]}".replace("\\", "/")
            lines.append(f"[{key}]: {target}")
        lines.append("")

    if cfg.get("assets"):
        lines.append("<!-- Assets -->")
        for key in sorted(cfg["assets"].keys()):
            target = f"./{assets_root}/{cfg['assets'][key]}".replace("\\", "/")
            lines.append(f"[{key}]: {target}")
        lines.append("")

    lines.append(END)
    return "\n".join(lines)


def inject_reference_block(rendered: str, block: str) -> str:
    pattern = re.compile(
        re.escape(START) + r".*?" + re.escape(END),
        flags=re.DOTALL,
    )
    if not pattern.search(rendered):
        return rendered.rstrip() + "\n\n" + block + "\n"
    return pattern.sub(block, rendered).rstrip() + "\n"


def iter_config_targets(cfg: dict, root: Path):
    paths = cfg.get("paths", {})
    docs_root = paths.get("docs_root", "docs").strip("/")
    assets_root = paths.get("assets_root", "assets").strip("/")

    for key, value in cfg.get("docs", {}).items():
        yield "doc", key, root / docs_root / value

    for key, value in cfg.get("assets", {}).items():
        yield "asset", key, root / assets_root / value


def build_file_index(root: Path) -> dict[str, list[Path]]:
    index: dict[str, list[Path]] = {}
    ignored = {".git", "build", "__pycache__", ".venv", "venv", "node_modules"}
    for path in root.rglob("*"):
        if any(part in ignored for part in path.parts):
            continue
        if path.is_file():
            index.setdefault(path.name.lower(), []).append(path)
    return index


def suggest_replacements(target: Path, root: Path, index: dict[str, list[Path]], limit: int = 5) -> list[Path]:
    filename = target.name.lower()
    if filename in index:
        return index[filename][:limit]

    names = list(index.keys())
    close = difflib.get_close_matches(filename, names, n=limit, cutoff=0.68)
    suggestions: list[Path] = []
    for name in close:
        suggestions.extend(index[name])
        if len(suggestions) >= limit:
            break
    return suggestions[:limit]


def validate_targets(cfg: dict, root: Path, show_suggestions: bool = True) -> int:
    broken = []
    file_index = None

    for kind, key, target in iter_config_targets(cfg, root):
        if not target.exists():
            broken.append((kind, key, target))

    if not broken:
        print("OK: all configured README targets exist.")
        return 0

    if show_suggestions:
        file_index = build_file_index(root)

    print(f"BROKEN CONFIG TARGETS: {len(broken)} problem(s)")
    for kind, key, target in broken:
        print(f"\n- [{kind}] {key}")
        print(f"  configured path: {relpath(target, root)}")
        if show_suggestions and file_index is not None:
            suggestions = suggest_replacements(target, root, file_index)
            if suggestions:
                print("  possible replacements:")
                for suggestion in suggestions:
                    print(f"    - {relpath(suggestion, root)}")
            else:
                print("  possible replacements: none found")

    return 1


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate README.md from config + template.")
    parser.add_argument("--root", default=".", help="Project root. Default: current directory.")
    parser.add_argument("--config", default="readme.config.toml", help="Config file relative to root.")
    parser.add_argument("--template", default="README.template.md", help="Template file relative to root.")
    parser.add_argument("--output", default="README.md", help="Output file relative to root.")
    parser.add_argument("--check", action="store_true", help="Validate config paths without writing README.")
    parser.add_argument("--no-suggest", action="store_true", help="Do not suggest replacement paths for broken targets.")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    config_path = root / args.config
    template_path = root / args.template
    output_path = root / args.output

    if not config_path.exists():
        print(f"ERROR: config not found: {relpath(config_path, root)}", file=sys.stderr)
        return 2
    if not template_path.exists() and not args.check:
        print(f"ERROR: template not found: {relpath(template_path, root)}", file=sys.stderr)
        return 2

    try:
        cfg = load_toml(config_path)
    except Exception as exc:
        print(f"ERROR: failed to read config: {exc}", file=sys.stderr)
        return 2

    validation_status = validate_targets(cfg, root, show_suggestions=not args.no_suggest)
    if args.check:
        return validation_status

    template = template_path.read_text(encoding="utf-8")
    try:
        rendered = render_inline_placeholders(template, cfg)
        reference_block = build_reference_block(cfg)
        output = inject_reference_block(rendered, reference_block)
    except Exception as exc:
        print(f"ERROR: failed to render README: {exc}", file=sys.stderr)
        return 2

    output_path.write_text(output, encoding="utf-8")
    print(f"Wrote {relpath(output_path, root)}")

    if validation_status != 0:
        print("WARNING: README was generated, but some configured targets are broken.")
    return validation_status


if __name__ == "__main__":
    raise SystemExit(main())
