name: Update Metrics

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate mana flow monitor
        uses: lowlighter/metrics@latest
        with:
          filename: profile/mana-flow-monitor.svg
          token: ${{ secrets.METRICS_TOKEN }}

          user: SaydRomey
          template: classic
          base: activity, metadata
          config_timezone: America/Montreal

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year